# Generated by Django 3.1.7 on 2021-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210330_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'job'), ('warning', 'house-work'), ('primary', 'self-study')], max_length=50),
        ),
    ]
